/**
 * Formula Lab — the reference cards.
 *
 * ADDING A CARD
 * -------------
 * Copy a block below and change the fields. The list, the search, the
 * calculator and the animation all read from here, so nothing else needs
 * editing to add a formula.
 *
 *   id      unique lowercase key, no spaces (it is also the page's #link)
 *   sub     physics | chemistry | math | engineering | space
 *   t       the name shown as the heading
 *   f       the formula, written out with real symbols
 *   m       one sentence saying what it means, in plain words
 *   age     rough age the idea starts making sense, e.g. "11+"
 *   vars    { symbol: ["what it is", "units"] } for every part of the formula
 *   solve   one entry per thing the calculator can work out:
 *             { for: "v", needs: ["d","t"], fn: function (x) { return x.d / x.t } }
 *   ex      a worked example: which value to solve for, the numbers, and a
 *           sentence of context. The calculator opens pre-filled with these.
 *   why     why it matters — the line a child actually remembers
 *   tags    extra words to make it findable in search
 *
 * A card with no `solve` (a chemical reaction, say) shows a `note` instead of
 * a calculator. To give a card an animation, add its id to VIZ_MAP in viz.js.
 *
 * Every example is run through its own solver when the page is tested, so a
 * card whose numbers do not work fails rather than reaching a child.
 */
(function () {
  "use strict";

  let cards = [];



  cards = cards.concat([
  { id:"speed", sub:"physics", t:"Speed", f:"v = d ÷ t", age:"9+",
    m:"How fast something moves: the distance it covered divided by the time it took.",
    vars:{ v:["speed","m/s"], d:["distance","m"], t:["time","s"] },
    solve:[ {for:"v",needs:["d","t"],fn:function(x){return x.d/x.t}},
            {for:"d",needs:["v","t"],fn:function(x){return x.v*x.t}},
            {for:"t",needs:["d","v"],fn:function(x){return x.d/x.v}} ],
    ex:{ for:"v", vals:{d:100,t:12.5}, says:"A cheetah covers 100 metres in 12.5 seconds." },
    why:"Every speed limit sign, every race result, and every \"are we there yet?\" is this one formula.",
    tags:"velocity distance time how fast" },

  { id:"acceleration", sub:"physics", t:"Acceleration", f:"a = (v₂ − v₁) ÷ t", age:"11+",
    m:"How quickly speed changes. Speeding up is positive, slowing down is negative.",
    vars:{ a:["acceleration","m/s²"], v1:["starting speed","m/s"], v2:["ending speed","m/s"], t:["time taken","s"] },
    solve:[ {for:"a",needs:["v1","v2","t"],fn:function(x){return (x.v2-x.v1)/x.t}} ],
    ex:{ for:"a", vals:{v1:0,v2:27,t:6}, says:"A car goes from a standstill to 27 m/s (about 60 mph) in 6 seconds." },
    why:"Acceleration is what you actually feel in a car or a roller coaster. Steady speed feels like nothing at all.",
    tags:"speeding up slowing down change in velocity" },

  { id:"newton2", sub:"physics", t:"Newton's Second Law", f:"F = m × a", age:"11+",
    m:"The push or pull on an object equals its mass times how fast it speeds up.",
    vars:{ F:["force","N"], m:["mass","kg"], a:["acceleration","m/s²"] },
    solve:[ {for:"F",needs:["m","a"],fn:function(x){return x.m*x.a}},
            {for:"a",needs:["F","m"],fn:function(x){return x.F/x.m}},
            {for:"m",needs:["F","a"],fn:function(x){return x.F/x.a}} ],
    ex:{ for:"F", vals:{m:1200,a:3}, says:"A 1200 kg car accelerating at 3 m/s² needs this much force from the engine." },
    why:"This is why a loaded shopping cart is harder to get moving than an empty one. Same push, more mass, less acceleration.",
    tags:"force mass acceleration newton" },

  { id:"weight", sub:"physics", t:"Weight", f:"W = m × g", age:"9+",
    m:"Weight is the pull of gravity on your mass. Mass never changes; weight does.",
    vars:{ W:["weight","N"], m:["mass","kg"], g:["gravity strength","m/s²"] },
    solve:[ {for:"W",needs:["m","g"],fn:function(x){return x.m*x.g}},
            {for:"m",needs:["W","g"],fn:function(x){return x.W/x.g}} ],
    ex:{ for:"W", vals:{m:40,g:9.8}, says:"A 40 kg kid standing on Earth, where g = 9.8 m/s²." },
    why:"Change g to 1.6 and you get your weight on the Moon. Your mass stayed exactly the same.",
    tags:"gravity mass moon newtons" },

  { id:"momentum", sub:"physics", t:"Momentum", f:"p = m × v", age:"12+",
    m:"How hard something is to stop: mass times speed.",
    vars:{ p:["momentum","kg·m/s"], m:["mass","kg"], v:["speed","m/s"] },
    solve:[ {for:"p",needs:["m","v"],fn:function(x){return x.m*x.v}},
            {for:"v",needs:["p","m"],fn:function(x){return x.p/x.m}} ],
    ex:{ for:"p", vals:{m:0.045,v:70}, says:"A golf ball (45 grams) leaving the club at 70 m/s." },
    why:"A slow truck and a fast bullet can carry the same momentum. That is why both are dangerous.",
    tags:"stopping crash collision" },

  { id:"impulse", sub:"physics", t:"Impulse", f:"J = F × t", age:"13+",
    m:"A force spread over time. The same change in momentum can come from a big force briefly or a small force for longer.",
    vars:{ J:["impulse","N·s"], F:["force","N"], t:["time force acts","s"] },
    solve:[ {for:"J",needs:["F","t"],fn:function(x){return x.F*x.t}},
            {for:"F",needs:["J","t"],fn:function(x){return x.J/x.t}} ],
    ex:{ for:"F", vals:{J:900,t:0.6}, says:"An airbag stretches a 900 N·s stop over 0.6 seconds instead of 0.05." },
    why:"Airbags, crash helmets, and crumple zones all work by making t bigger so F gets smaller.",
    tags:"airbag safety crumple zone momentum change" },

  { id:"ke", sub:"physics", t:"Kinetic Energy", f:"KE = ½ × m × v²", age:"12+",
    m:"The energy of anything that is moving. Doubling the speed gives four times the energy.",
    vars:{ KE:["kinetic energy","J"], m:["mass","kg"], v:["speed","m/s"] },
    solve:[ {for:"KE",needs:["m","v"],fn:function(x){return 0.5*x.m*x.v*x.v}},
            {for:"v",needs:["KE","m"],fn:function(x){return Math.sqrt(2*x.KE/x.m)}} ],
    ex:{ for:"KE", vals:{m:1200,v:20}, says:"A 1200 kg car travelling at 20 m/s." },
    why:"Because of the v², a car at 40 mph carries four times the crash energy of the same car at 20 mph. Not twice.",
    tags:"energy movement crash speed squared" },

  { id:"pe", sub:"physics", t:"Gravitational Potential Energy", f:"PE = m × g × h", age:"12+",
    m:"Stored energy from being up high. Let go and it turns into motion.",
    vars:{ PE:["potential energy","J"], m:["mass","kg"], g:["gravity strength","m/s²"], h:["height","m"] },
    solve:[ {for:"PE",needs:["m","g","h"],fn:function(x){return x.m*x.g*x.h}},
            {for:"h",needs:["PE","m","g"],fn:function(x){return x.PE/(x.m*x.g)}} ],
    ex:{ for:"PE", vals:{m:60,g:9.8,h:10}, says:"A 60 kg person at the top of a 10 metre diving platform." },
    why:"Roller coasters spend all their energy budget on the first hill. Every hill after that has to be shorter.",
    tags:"height stored energy roller coaster" },

  { id:"work", sub:"physics", t:"Work", f:"W = F × d", age:"11+",
    m:"Energy transferred by pushing something along. No movement means no work, no matter how tired you get.",
    vars:{ W:["work","J"], F:["force","N"], d:["distance moved","m"] },
    solve:[ {for:"W",needs:["F","d"],fn:function(x){return x.F*x.d}},
            {for:"F",needs:["W","d"],fn:function(x){return x.W/x.d}} ],
    ex:{ for:"W", vals:{F:150,d:4}, says:"Pushing a heavy box with 150 N of force across 4 metres of floor." },
    why:"Holding a heavy bag still does zero work in physics, even though your arms strongly disagree.",
    tags:"energy push force distance joules" },

  { id:"power", sub:"physics", t:"Power", f:"P = W ÷ t", age:"12+",
    m:"How fast energy gets used or delivered. Same job done quicker means more power.",
    vars:{ P:["power","W"], W:["work or energy","J"], t:["time","s"] },
    solve:[ {for:"P",needs:["W","t"],fn:function(x){return x.W/x.t}},
            {for:"t",needs:["W","P"],fn:function(x){return x.W/x.P}} ],
    ex:{ for:"P", vals:{W:6000,t:10}, says:"Climbing stairs using 6000 J of energy in 10 seconds." },
    why:"A 100 W lightbulb and a 100 W person climbing stairs are burning energy at exactly the same rate.",
    tags:"watts energy rate horsepower" },

  { id:"density", sub:"physics", t:"Density", f:"ρ = m ÷ V", age:"10+",
    m:"How much stuff is packed into a space. Low density floats, high density sinks.",
    vars:{ rho:["density","kg/m³"], m:["mass","kg"], V:["volume","m³"] },
    solve:[ {for:"rho",needs:["m","V"],fn:function(x){return x.m/x.V}},
            {for:"m",needs:["rho","V"],fn:function(x){return x.rho*x.V}},
            {for:"V",needs:["m","rho"],fn:function(x){return x.m/x.rho}} ],
    ex:{ for:"rho", vals:{m:7.8,V:0.001}, says:"A 7.8 kg block of steel taking up 0.001 m³ (one litre)." },
    why:"Water is 1000 kg/m³. Anything less than that floats in it, which is the whole reason ships are hollow.",
    tags:"float sink mass volume packed" },

  { id:"pressure", sub:"physics", t:"Pressure", f:"P = F ÷ A", age:"11+",
    m:"Force squeezed into an area. Same force on a smaller area means much higher pressure.",
    vars:{ P:["pressure","Pa"], F:["force","N"], A:["area","m²"] },
    solve:[ {for:"P",needs:["F","A"],fn:function(x){return x.F/x.A}},
            {for:"A",needs:["F","P"],fn:function(x){return x.F/x.P}} ],
    ex:{ for:"P", vals:{F:600,A:0.03}, says:"A 600 N person standing on two feet covering 0.03 m²." },
    why:"This is why snowshoes work and why a drawing pin goes into a wall: same push, wildly different area.",
    tags:"squeeze area force pascals snowshoe" },

  { id:"hooke", sub:"physics", t:"Hooke's Law (springs)", f:"F = k × x", age:"12+",
    m:"The further you stretch a spring, the harder it pulls back, in a straight line relationship.",
    vars:{ F:["force","N"], k:["spring stiffness","N/m"], x:["stretch","m"] },
    solve:[ {for:"F",needs:["k","x"],fn:function(x){return x.k*x.x}},
            {for:"x",needs:["F","k"],fn:function(x){return x.F/x.k}} ],
    ex:{ for:"F", vals:{k:250,x:0.08}, says:"A spring with stiffness 250 N/m stretched 8 cm." },
    why:"Every kitchen scale, trampoline, and car suspension is this equation doing its job.",
    tags:"spring stretch bounce stiffness" },

  { id:"wavespeed", sub:"physics", t:"Wave Speed", f:"v = f × λ", age:"12+",
    m:"How fast a wave travels: how many waves per second times how long each one is.",
    vars:{ v:["wave speed","m/s"], f:["frequency","Hz"], lam:["wavelength","m"] },
    solve:[ {for:"v",needs:["f","lam"],fn:function(x){return x.f*x.lam}},
            {for:"f",needs:["v","lam"],fn:function(x){return x.v/x.lam}},
            {for:"lam",needs:["v","f"],fn:function(x){return x.v/x.f}} ],
    ex:{ for:"v", vals:{f:440,lam:0.78}, says:"Concert A on a piano: 440 waves per second, each 0.78 m long." },
    why:"Sound, light, radio, and ocean waves all obey this. Only the numbers change.",
    tags:"sound light frequency wavelength music" },

  { id:"period", sub:"physics", t:"Frequency and Period", f:"f = 1 ÷ T", age:"11+",
    m:"Frequency is how many times per second. Period is how long one cycle takes. They are upside down versions of each other.",
    vars:{ f:["frequency","Hz"], T:["period","s"] },
    solve:[ {for:"f",needs:["T"],fn:function(x){return 1/x.T}},
            {for:"T",needs:["f"],fn:function(x){return 1/x.f}} ],
    ex:{ for:"f", vals:{T:0.02}, says:"A guitar string that takes 0.02 seconds to complete one full vibration." },
    why:"A 60 Hz screen refreshes every 1/60th of a second. Same fact, said two ways.",
    tags:"hertz cycles per second pendulum refresh rate" },

  { id:"ohm", sub:"physics", t:"Ohm's Law", f:"V = I × R", age:"12+",
    m:"Voltage pushes, resistance holds back, and current is what actually flows.",
    vars:{ V:["voltage","V"], I:["current","A"], R:["resistance","Ω"] },
    solve:[ {for:"V",needs:["I","R"],fn:function(x){return x.I*x.R}},
            {for:"I",needs:["V","R"],fn:function(x){return x.V/x.R}},
            {for:"R",needs:["V","I"],fn:function(x){return x.V/x.I}} ],
    ex:{ for:"I", vals:{V:9,R:330}, says:"A 9 V battery pushing through a 330 Ω resistor." },
    why:"If you build anything with an LED, this equation tells you which resistor stops it burning out.",
    tags:"electricity voltage current resistance circuit led" },

  { id:"epower", sub:"physics", t:"Electrical Power", f:"P = V × I", age:"12+",
    m:"How fast an electrical device uses energy.",
    vars:{ P:["power","W"], V:["voltage","V"], I:["current","A"] },
    solve:[ {for:"P",needs:["V","I"],fn:function(x){return x.V*x.I}},
            {for:"I",needs:["P","V"],fn:function(x){return x.P/x.V}} ],
    ex:{ for:"P", vals:{V:120,I:12.5}, says:"A hairdryer pulling 12.5 A from a 120 V wall socket." },
    why:"Your electricity bill is literally this number, multiplied by how many hours you left it on.",
    tags:"watts electricity bill appliance" },

  { id:"efficiency", sub:"physics", t:"Efficiency", f:"efficiency = (useful ÷ total) × 100", age:"11+",
    m:"What fraction of the energy you put in actually did the job you wanted.",
    vars:{ eff:["efficiency","%"], useful:["useful energy out","J"], total:["total energy in","J"] },
    solve:[ {for:"eff",needs:["useful","total"],fn:function(x){return (x.useful/x.total)*100}} ],
    ex:{ for:"eff", vals:{useful:5,total:100}, says:"An old filament bulb: 100 J of electricity, only about 5 J of light." },
    why:"The other 95 J became heat. That is why old bulbs were hot and LEDs are not.",
    tags:"waste energy percent led bulb machine" },

  { id:"freefall", sub:"physics", t:"Falling Distance", f:"d = ½ × g × t²", age:"12+",
    m:"How far something falls if you drop it, ignoring air resistance.",
    vars:{ d:["distance fallen","m"], g:["gravity strength","m/s²"], t:["time falling","s"] },
    solve:[ {for:"d",needs:["g","t"],fn:function(x){return 0.5*x.g*x.t*x.t}},
            {for:"t",needs:["d","g"],fn:function(x){return Math.sqrt(2*x.d/x.g)}} ],
    ex:{ for:"d", vals:{g:9.8,t:3}, says:"A rock dropped off a cliff, falling for 3 seconds." },
    why:"Count the seconds until you hear a stone hit the bottom of a well, and this tells you how deep it is.",
    tags:"gravity drop fall cliff well" },

  { id:"projectile", sub:"physics", t:"Projectile Range", f:"R = v² × sin(2θ) ÷ g", age:"14+",
    m:"How far a thrown or launched object lands, on flat ground, ignoring air.",
    vars:{ R:["range","m"], v:["launch speed","m/s"], th:["launch angle","°"], g:["gravity strength","m/s²"] },
    solve:[ {for:"R",needs:["v","th","g"],fn:function(x){return (x.v*x.v*Math.sin(2*x.th*Math.PI/180))/x.g}} ],
    ex:{ for:"R", vals:{v:20,th:45,g:9.8}, says:"A ball launched at 20 m/s at a 45 degree angle." },
    why:"45 degrees gives the maximum range, and this formula is why every catapult and water balloon fight ends up there.",
    tags:"throw launch angle catapult cannon distance" },

  { id:"centripetal", sub:"physics", t:"Centripetal Force", f:"F = m × v² ÷ r", age:"14+",
    m:"The inward pull needed to keep something moving in a circle instead of flying off straight.",
    vars:{ F:["force","N"], m:["mass","kg"], v:["speed","m/s"], r:["radius of circle","m"] },
    solve:[ {for:"F",needs:["m","v","r"],fn:function(x){return x.m*x.v*x.v/x.r}} ],
    ex:{ for:"F", vals:{m:0.5,v:6,r:1.2}, says:"Swinging a 0.5 kg ball on a 1.2 m string at 6 m/s." },
    why:"Nothing pushes you outward on a fast corner. The car is pulling you inward, and your body is trying to go straight.",
    tags:"circle spin loop roller coaster corner" },

  { id:"gravitation", sub:"physics", t:"Universal Gravitation", f:"F = G × m₁ × m₂ ÷ r²", age:"14+",
    m:"Every object with mass pulls on every other object. Bigger masses pull harder, distance weakens it fast.",
    vars:{ F:["force","N"], m1:["first mass","kg"], m2:["second mass","kg"], r:["distance between centres","m"] },
    solve:[ {for:"F",needs:["m1","m2","r"],fn:function(x){return 6.674e-11*x.m1*x.m2/(x.r*x.r)}} ],
    ex:{ for:"F", vals:{m1:5.97e24,m2:70,r:6371000}, says:"The Earth pulling on a 70 kg person standing on its surface." },
    why:"The answer comes out to about 687 N, which is exactly that person's weight. Same force, two different formulas.",
    tags:"gravity planets orbit newton moon" },

  { id:"buoyancy", sub:"physics", t:"Buoyant Force", f:"F = ρ × V × g", age:"13+",
    m:"The upward push of a fluid equals the weight of the fluid the object shoved out of the way.",
    vars:{ F:["buoyant force","N"], rho:["fluid density","kg/m³"], V:["volume displaced","m³"], g:["gravity strength","m/s²"] },
    solve:[ {for:"F",needs:["rho","V","g"],fn:function(x){return x.rho*x.V*x.g}} ],
    ex:{ for:"F", vals:{rho:1000,V:0.05,g:9.8}, says:"An object pushing 0.05 m³ (50 litres) of water out of the way." },
    why:"Archimedes worked this out in a bathtub. A steel ship floats because its hull displaces a huge volume of water.",
    tags:"float ship archimedes water displacement submarine" },

  { id:"heat", sub:"physics", t:"Heat Energy", f:"Q = m × c × ΔT", age:"13+",
    m:"How much energy it takes to change something's temperature.",
    vars:{ Q:["heat energy","J"], m:["mass","kg"], c:["specific heat","J/kg°C"], dT:["temperature change","°C"] },
    solve:[ {for:"Q",needs:["m","c","dT"],fn:function(x){return x.m*x.c*x.dT}},
            {for:"dT",needs:["Q","m","c"],fn:function(x){return x.Q/(x.m*x.c)}} ],
    ex:{ for:"Q", vals:{m:0.5,c:4186,dT:80}, says:"Heating half a litre of water (c = 4186) from 20 °C to 100 °C." },
    why:"Water has an unusually high c, which is why it takes forever to boil and why oceans keep coastal towns mild.",
    tags:"temperature boiling specific heat kettle energy" }
  ]);

  cards = cards.concat([
  { id:"moles", sub:"chemistry", t:"Moles from Mass", f:"n = m ÷ M", age:"13+",
    m:"A mole is just a counting word, like \"dozen\", but for atoms. This turns grams into moles.",
    vars:{ n:["moles","mol"], m:["mass","g"], M:["molar mass","g/mol"] },
    solve:[ {for:"n",needs:["m","M"],fn:function(x){return x.m/x.M}},
            {for:"m",needs:["n","M"],fn:function(x){return x.n*x.M}},
            {for:"M",needs:["m","n"],fn:function(x){return x.m/x.n}} ],
    ex:{ for:"n", vals:{m:36,M:18}, says:"36 grams of water, which has a molar mass of 18 g/mol." },
    why:"Chemists cannot count atoms one at a time, so they weigh them instead. This is the conversion.",
    tags:"mole mass molar counting atoms" },

  { id:"particles", sub:"chemistry", t:"Counting Particles", f:"N = n × 6.022×10²³", age:"13+",
    m:"How many actual atoms or molecules are in a number of moles.",
    vars:{ N:["number of particles","particles"], n:["moles","mol"] },
    solve:[ {for:"N",needs:["n"],fn:function(x){return x.n*6.022e23}},
            {for:"n",needs:["N"],fn:function(x){return x.N/6.022e23}} ],
    ex:{ for:"N", vals:{n:2}, says:"Two moles of anything at all." },
    why:"That number, Avogadro's number, is so large that a mole of grains of sand would bury the whole Earth.",
    tags:"avogadro number atoms molecules count" },

  { id:"molarity", sub:"chemistry", t:"Molarity (concentration)", f:"c = n ÷ V", age:"14+",
    m:"How strong a solution is: moles of stuff dissolved per litre of liquid.",
    vars:{ c:["concentration","mol/L"], n:["moles of solute","mol"], V:["volume of solution","L"] },
    solve:[ {for:"c",needs:["n","V"],fn:function(x){return x.n/x.V}},
            {for:"n",needs:["c","V"],fn:function(x){return x.c*x.V}},
            {for:"V",needs:["n","c"],fn:function(x){return x.n/x.c}} ],
    ex:{ for:"c", vals:{n:0.5,V:2}, says:"Half a mole of salt dissolved in 2 litres of water." },
    why:"Strong or weak is not a vibe in chemistry. It is a number, and this is it.",
    tags:"concentration solution dissolved strength molar" },

  { id:"dilution", sub:"chemistry", t:"Dilution", f:"C₁ × V₁ = C₂ × V₂", age:"14+",
    m:"Adding water makes a solution weaker, but the amount of dissolved stuff stays exactly the same.",
    vars:{ C1:["starting concentration","mol/L"], V1:["starting volume","L"], C2:["final concentration","mol/L"], V2:["final volume","L"] },
    solve:[ {for:"V2",needs:["C1","V1","C2"],fn:function(x){return x.C1*x.V1/x.C2}},
            {for:"C2",needs:["C1","V1","V2"],fn:function(x){return x.C1*x.V1/x.V2}},
            {for:"V1",needs:["C1","C2","V2"],fn:function(x){return x.C2*x.V2/x.C1}} ],
    ex:{ for:"V2", vals:{C1:2,V1:0.25,C2:0.5}, says:"Taking 0.25 L of 2 mol/L acid and watering it down to 0.5 mol/L." },
    why:"This is how every lab, every cleaning product, and every juice concentrate gets to the right strength.",
    tags:"water down weaker concentrate juice acid" },

  { id:"idealgas", sub:"chemistry", t:"Ideal Gas Law", f:"P × V = n × R × T", age:"15+",
    m:"Ties together the pressure, volume, amount, and temperature of a gas in one equation.",
    vars:{ P:["pressure","kPa"], V:["volume","L"], n:["moles of gas","mol"], T:["temperature","K"] },
    solve:[ {for:"P",needs:["n","T","V"],fn:function(x){return x.n*8.314*x.T/x.V}},
            {for:"V",needs:["n","T","P"],fn:function(x){return x.n*8.314*x.T/x.P}},
            {for:"n",needs:["P","V","T"],fn:function(x){return x.P*x.V/(8.314*x.T)}} ],
    ex:{ for:"P", vals:{n:1,T:273.15,V:22.4}, says:"One mole of gas at 0 °C in 22.4 litres. Uses R = 8.314 L·kPa/(mol·K)." },
    why:"Temperature here must be in kelvin, always. Using celsius is the single most common mistake in chemistry class.",
    tags:"gas pressure volume temperature kelvin balloon" },

  { id:"boyle", sub:"chemistry", t:"Boyle's Law", f:"P₁ × V₁ = P₂ × V₂", age:"13+",
    m:"Squeeze a gas into half the space and its pressure doubles, as long as temperature stays put.",
    vars:{ P1:["starting pressure","kPa"], V1:["starting volume","L"], P2:["final pressure","kPa"], V2:["final volume","L"] },
    solve:[ {for:"V2",needs:["P1","V1","P2"],fn:function(x){return x.P1*x.V1/x.P2}},
            {for:"P2",needs:["P1","V1","V2"],fn:function(x){return x.P1*x.V1/x.V2}} ],
    ex:{ for:"P2", vals:{P1:101,V1:2,V2:0.5}, says:"Squashing 2 litres of air at normal pressure down into 0.5 litres." },
    why:"This is what your ears feel on a plane and what makes a syringe work.",
    tags:"squeeze gas pressure volume syringe ears plane" },

  { id:"charles", sub:"chemistry", t:"Charles's Law", f:"V₁ ÷ T₁ = V₂ ÷ T₂", age:"13+",
    m:"Heat a gas and it expands, in direct proportion to its temperature in kelvin.",
    vars:{ V1:["starting volume","L"], T1:["starting temperature","K"], V2:["final volume","L"], T2:["final temperature","K"] },
    solve:[ {for:"V2",needs:["V1","T1","T2"],fn:function(x){return x.V1*x.T2/x.T1}},
            {for:"T2",needs:["V1","T1","V2"],fn:function(x){return x.T1*x.V2/x.V1}} ],
    ex:{ for:"V2", vals:{V1:1,T1:293,T2:373}, says:"A 1 litre balloon warmed from 20 °C (293 K) to 100 °C (373 K)." },
    why:"Hot air balloons fly on this. Warm the air, it expands, the same balloon now holds less mass than the air around it.",
    tags:"heat expand balloon kelvin hot air" },

  { id:"gaylussac", sub:"chemistry", t:"Gay-Lussac's Law", f:"P₁ ÷ T₁ = P₂ ÷ T₂", age:"14+",
    m:"In a sealed rigid container, heating the gas raises the pressure.",
    vars:{ P1:["starting pressure","kPa"], T1:["starting temperature","K"], P2:["final pressure","kPa"], T2:["final temperature","K"] },
    solve:[ {for:"P2",needs:["P1","T1","T2"],fn:function(x){return x.P1*x.T2/x.T1}},
            {for:"T2",needs:["P1","T1","P2"],fn:function(x){return x.T1*x.P2/x.P1}} ],
    ex:{ for:"P2", vals:{P1:101,T1:293,T2:373}, says:"A sealed can of air heated from 20 °C to 100 °C." },
    why:"It is exactly why aerosol cans say do not incinerate, and why car tyre pressure rises on a long drive.",
    tags:"sealed can pressure heat aerosol tyre explode" },

  { id:"combinedgas", sub:"chemistry", t:"Combined Gas Law", f:"(P₁V₁) ÷ T₁ = (P₂V₂) ÷ T₂", age:"15+",
    m:"Boyle, Charles, and Gay-Lussac rolled into one, for when two things change at once.",
    vars:{ P1:["starting pressure","kPa"], V1:["starting volume","L"], T1:["starting temperature","K"], P2:["final pressure","kPa"], V2:["final volume","L"], T2:["final temperature","K"] },
    solve:[ {for:"V2",needs:["P1","V1","T1","P2","T2"],fn:function(x){return x.P1*x.V1*x.T2/(x.T1*x.P2)}},
            {for:"P2",needs:["P1","V1","T1","V2","T2"],fn:function(x){return x.P1*x.V1*x.T2/(x.T1*x.V2)}} ],
    ex:{ for:"V2", vals:{P1:101,V1:2,T1:293,P2:50,T2:250}, says:"A weather balloon rising: pressure drops to 50 kPa and it gets colder, 250 K." },
    why:"Weather balloons swell as they climb because pressure falls faster than temperature does.",
    tags:"weather balloon altitude gas combined" },

  { id:"ph", sub:"chemistry", t:"pH", f:"pH = −log₁₀[H⁺]", age:"14+",
    m:"How acidic something is. Below 7 is acid, 7 is neutral, above 7 is basic.",
    vars:{ pH:["pH",""], H:["hydrogen ion concentration","mol/L"] },
    solve:[ {for:"pH",needs:["H"],fn:function(x){return -Math.log(x.H)/Math.LN10}},
            {for:"H",needs:["pH"],fn:function(x){return Math.pow(10,-x.pH)}} ],
    ex:{ for:"pH", vals:{H:0.0001}, says:"A solution with a hydrogen ion concentration of 0.0001 mol/L." },
    why:"The scale is logarithmic: pH 3 is ten times more acidic than pH 4, not a little bit more.",
    tags:"acid base alkaline logarithm lemon soap" },

  { id:"poh", sub:"chemistry", t:"pH and pOH", f:"pH + pOH = 14", age:"15+",
    m:"Acids and bases are two ends of one scale. Know one number and you know the other.",
    vars:{ pH:["pH",""], pOH:["pOH",""] },
    solve:[ {for:"pOH",needs:["pH"],fn:function(x){return 14-x.pH}},
            {for:"pH",needs:["pOH"],fn:function(x){return 14-x.pOH}} ],
    ex:{ for:"pOH", vals:{pH:3}, says:"A strong acid sitting at pH 3." },
    why:"This holds at room temperature in water, which covers almost everything you meet in school chemistry.",
    tags:"acid base scale hydroxide" },

  { id:"percentyield", sub:"chemistry", t:"Percent Yield", f:"yield = (actual ÷ theoretical) × 100", age:"14+",
    m:"How much product you really got, compared to the most you could possibly have got.",
    vars:{ yieldp:["percent yield","%"], actual:["actual mass made","g"], theo:["theoretical mass","g"] },
    solve:[ {for:"yieldp",needs:["actual","theo"],fn:function(x){return x.actual/x.theo*100}},
            {for:"actual",needs:["yieldp","theo"],fn:function(x){return x.yieldp*x.theo/100}} ],
    ex:{ for:"yieldp", vals:{actual:6.8,theo:8.5}, says:"A reaction that should have made 8.5 g but actually made 6.8 g." },
    why:"Real reactions always lose some product. A 100 percent yield almost always means a mistake in the measuring.",
    tags:"reaction product lab yield efficiency" },

  { id:"percentcomp", sub:"chemistry", t:"Percent Composition", f:"% = (part ÷ whole) × 100", age:"13+",
    m:"What fraction of a compound's mass comes from one particular element.",
    vars:{ pct:["percent","%"], part:["mass of the element","g"], whole:["mass of the compound","g"] },
    solve:[ {for:"pct",needs:["part","whole"],fn:function(x){return x.part/x.whole*100}} ],
    ex:{ for:"pct", vals:{part:2,whole:18}, says:"Hydrogen in water: 2 g of hydrogen in every 18 g of water." },
    why:"Water is about 11 percent hydrogen by mass but two thirds hydrogen by atom count. Mass and count are different questions.",
    tags:"composition element mass fraction water" },

  { id:"molarvolume", sub:"chemistry", t:"Molar Volume at STP", f:"V = n × 22.4", age:"14+",
    m:"At standard temperature and pressure, one mole of any gas fills 22.4 litres.",
    vars:{ V:["volume","L"], n:["moles of gas","mol"] },
    solve:[ {for:"V",needs:["n"],fn:function(x){return x.n*22.4}},
            {for:"n",needs:["V"],fn:function(x){return x.V/22.4}} ],
    ex:{ for:"V", vals:{n:3}, says:"Three moles of any gas at 0 °C and 1 atmosphere." },
    why:"Any gas. Hydrogen, oxygen, chlorine, it does not matter. Gas particles are so far apart that the identity stops mattering.",
    tags:"gas volume stp standard mole" },

  { id:"combustion", sub:"chemistry", t:"Combustion Reaction", f:"fuel + O₂ → CO₂ + H₂O", age:"11+",
    m:"Burning. A fuel containing carbon and hydrogen meets oxygen and releases energy.",
    vars:{},
    note:"Example: CH₄ + 2O₂ → CO₂ + 2H₂O (burning methane, the gas in a stove)",
    why:"Candles, campfires, car engines, and your own body burning sugar all follow this same pattern.",
    tags:"burning fire fuel oxygen carbon dioxide methane candle" },

  { id:"neutralization", sub:"chemistry", t:"Neutralization Reaction", f:"acid + base → salt + water", age:"12+",
    m:"An acid and a base cancel each other out, leaving a salt and plain water behind.",
    vars:{},
    note:"Example: HCl + NaOH → NaCl + H₂O (hydrochloric acid plus lye makes table salt and water)",
    why:"Antacid tablets are this reaction happening in your stomach, and the salt it makes is genuinely just salt.",
    tags:"acid base salt water antacid stomach" },

  { id:"photosynthesis", sub:"chemistry", t:"Photosynthesis", f:"6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂", age:"10+",
    m:"Plants take carbon dioxide and water, add sunlight, and build sugar. Oxygen is the leftover.",
    vars:{},
    note:"Respiration runs this exact equation backwards: sugar + oxygen → carbon dioxide + water + energy",
    why:"Every bit of oxygen you have ever breathed was a waste product from a plant doing this.",
    tags:"plants sunlight oxygen sugar glucose leaves" },

  { id:"rusting", sub:"chemistry", t:"Rusting (oxidation)", f:"4Fe + 3O₂ → 2Fe₂O₃", age:"11+",
    m:"Iron meets oxygen, usually helped along by water, and slowly turns into rust.",
    vars:{},
    note:"Rust takes up more space than the iron it came from, which is why rusty metal flakes and swells",
    why:"It is the same chemistry as burning, just running thousands of times slower.",
    tags:"rust iron oxygen oxidation corrosion metal" }
  ]);

  cards = cards.concat([
  { id:"area-rect", sub:"math", t:"Area of a Rectangle", f:"A = w × h", age:"8+",
    m:"How much flat space a rectangle covers.",
    vars:{ A:["area","units²"], w:["width","units"], h:["height","units"] },
    solve:[ {for:"A",needs:["w","h"],fn:function(x){return x.w*x.h}},
            {for:"w",needs:["A","h"],fn:function(x){return x.A/x.h}} ],
    ex:{ for:"A", vals:{w:4,h:2.5}, says:"A rug 4 m wide and 2.5 m deep." },
    why:"Paint, carpet, and tiles are all sold by area, so this is the formula that decides how much you buy.",
    tags:"rectangle square space carpet paint" },

  { id:"area-tri", sub:"math", t:"Area of a Triangle", f:"A = ½ × b × h", age:"9+",
    m:"A triangle covers exactly half of the rectangle that would fit around it.",
    vars:{ A:["area","units²"], b:["base","units"], h:["height","units"] },
    solve:[ {for:"A",needs:["b","h"],fn:function(x){return 0.5*x.b*x.h}},
            {for:"h",needs:["A","b"],fn:function(x){return 2*x.A/x.b}} ],
    ex:{ for:"A", vals:{b:6,h:4}, says:"A triangle with a 6 cm base standing 4 cm tall." },
    why:"The height has to be straight up from the base, not along a slanted side. That trips up almost everyone once.",
    tags:"triangle base height half rectangle" },

  { id:"area-circle", sub:"math", t:"Area of a Circle", f:"A = π × r²", age:"10+",
    m:"How much space a circle covers, from its radius.",
    vars:{ A:["area","units²"], r:["radius","units"] },
    solve:[ {for:"A",needs:["r"],fn:function(x){return Math.PI*x.r*x.r}},
            {for:"r",needs:["A"],fn:function(x){return Math.sqrt(x.A/Math.PI)}} ],
    ex:{ for:"A", vals:{r:5}, says:"A circle with a radius of 5 cm." },
    why:"A 16 inch pizza is not twice a 8 inch pizza. Because of the r², it is four times the pizza.",
    tags:"circle radius pi pizza round" },

  { id:"circumference", sub:"math", t:"Circumference of a Circle", f:"C = 2 × π × r", age:"10+",
    m:"The distance all the way around a circle.",
    vars:{ C:["circumference","units"], r:["radius","units"] },
    solve:[ {for:"C",needs:["r"],fn:function(x){return 2*Math.PI*x.r}},
            {for:"r",needs:["C"],fn:function(x){return x.C/(2*Math.PI)}} ],
    ex:{ for:"C", vals:{r:0.35}, says:"A bicycle wheel with a 0.35 m radius." },
    why:"One turn of that wheel moves the bike exactly one circumference. That is how a bike computer measures distance.",
    tags:"circle around pi wheel perimeter" },

  { id:"vol-box", sub:"math", t:"Volume of a Box", f:"V = l × w × h", age:"9+",
    m:"How much space is inside a rectangular box.",
    vars:{ V:["volume","units³"], l:["length","units"], w:["width","units"], h:["height","units"] },
    solve:[ {for:"V",needs:["l","w","h"],fn:function(x){return x.l*x.w*x.h}} ],
    ex:{ for:"V", vals:{l:30,w:20,h:15}, says:"A shipping box 30 by 20 by 15 cm." },
    why:"Doubling every side does not double the volume. It makes it eight times bigger.",
    tags:"box volume space cuboid shipping" },

  { id:"vol-cyl", sub:"math", t:"Volume of a Cylinder", f:"V = π × r² × h", age:"11+",
    m:"A stack of circles: the area of the circle times how tall the stack is.",
    vars:{ V:["volume","units³"], r:["radius","units"], h:["height","units"] },
    solve:[ {for:"V",needs:["r","h"],fn:function(x){return Math.PI*x.r*x.r*x.h}},
            {for:"h",needs:["V","r"],fn:function(x){return x.V/(Math.PI*x.r*x.r)}} ],
    ex:{ for:"V", vals:{r:3.3,h:12}, says:"A drinks can about 3.3 cm in radius and 12 cm tall (answer in cm³, which is millilitres)." },
    why:"Cubic centimetres and millilitres are the same size, so this formula tells you the can holds about 410 mL.",
    tags:"cylinder can volume tube pipe" },

  { id:"vol-sphere", sub:"math", t:"Volume of a Sphere", f:"V = (4 ÷ 3) × π × r³", age:"12+",
    m:"How much space is inside a ball.",
    vars:{ V:["volume","units³"], r:["radius","units"] },
    solve:[ {for:"V",needs:["r"],fn:function(x){return (4/3)*Math.PI*Math.pow(x.r,3)}} ],
    ex:{ for:"V", vals:{r:11}, says:"A basketball with an 11 cm radius." },
    why:"Because of the r³, a ball twice as wide holds eight times as much air.",
    tags:"sphere ball volume radius cubed" },

  { id:"vol-cone", sub:"math", t:"Volume of a Cone", f:"V = (1 ÷ 3) × π × r² × h", age:"12+",
    m:"A cone holds exactly one third of the cylinder it fits inside.",
    vars:{ V:["volume","units³"], r:["radius","units"], h:["height","units"] },
    solve:[ {for:"V",needs:["r","h"],fn:function(x){return (1/3)*Math.PI*x.r*x.r*x.h}} ],
    ex:{ for:"V", vals:{r:3,h:10}, says:"An ice cream cone 3 cm across at the top and 10 cm deep." },
    why:"You can prove the one third with water, a paper cone, and a matching cylinder. It takes exactly three pours.",
    tags:"cone volume ice cream third cylinder" },

  { id:"sa-sphere", sub:"math", t:"Surface Area of a Sphere", f:"A = 4 × π × r²", age:"13+",
    m:"How much skin a ball has on the outside.",
    vars:{ A:["surface area","units²"], r:["radius","units"] },
    solve:[ {for:"A",needs:["r"],fn:function(x){return 4*Math.PI*x.r*x.r}} ],
    ex:{ for:"A", vals:{r:6371}, says:"The Earth, radius 6371 km (answer in km²)." },
    why:"It works out to about 510 million km², and roughly 71 percent of that is ocean.",
    tags:"sphere surface skin earth area" },

  { id:"pythagoras", sub:"math", t:"Pythagorean Theorem", f:"c = √(a² + b²)", age:"11+",
    m:"In a right angled triangle, the long side can be worked out from the two short ones.",
    vars:{ c:["long side (hypotenuse)","units"], a:["short side","units"], b:["other short side","units"] },
    solve:[ {for:"c",needs:["a","b"],fn:function(x){return Math.sqrt(x.a*x.a+x.b*x.b)}},
            {for:"a",needs:["c","b"],fn:function(x){return Math.sqrt(x.c*x.c-x.b*x.b)}} ],
    ex:{ for:"c", vals:{a:3,b:4}, says:"The classic 3 4 5 triangle." },
    why:"Builders use a 3 4 5 triangle to check a corner is truly square. It is 2500 year old maths still on job sites today.",
    tags:"triangle right angle hypotenuse square corner" },

  { id:"slope", sub:"math", t:"Slope of a Line", f:"m = (y₂ − y₁) ÷ (x₂ − x₁)", age:"12+",
    m:"How steep a line is: how far up divided by how far across.",
    vars:{ m:["slope",""], x1:["first x",""], y1:["first y",""], x2:["second x",""], y2:["second y",""] },
    solve:[ {for:"m",needs:["x1","y1","x2","y2"],fn:function(x){return (x.y2-x.y1)/(x.x2-x.x1)}} ],
    ex:{ for:"m", vals:{x1:1,y1:2,x2:5,y2:10}, says:"A line passing through the points (1, 2) and (5, 10)." },
    why:"Slope is just rise over run, and it is the same idea as a wheelchair ramp gradient or a ski run rating.",
    tags:"gradient steepness line graph rise run" },

  { id:"distance", sub:"math", t:"Distance Between Two Points", f:"d = √((x₂−x₁)² + (y₂−y₁)²)", age:"13+",
    m:"The straight line distance between two points on a grid.",
    vars:{ d:["distance",""], x1:["first x",""], y1:["first y",""], x2:["second x",""], y2:["second y",""] },
    solve:[ {for:"d",needs:["x1","y1","x2","y2"],fn:function(x){return Math.sqrt(Math.pow(x.x2-x.x1,2)+Math.pow(x.y2-x.y1,2))}} ],
    ex:{ for:"d", vals:{x1:0,y1:0,x2:6,y2:8}, says:"From the origin to the point (6, 8)." },
    why:"This is Pythagoras wearing a different hat, and it is exactly how a game works out if two things collided.",
    tags:"grid coordinates pythagoras game collision" },

  { id:"percent-change", sub:"math", t:"Percentage Change", f:"change = ((new − old) ÷ old) × 100", age:"11+",
    m:"How much something went up or down, as a percentage of where it started.",
    vars:{ pct:["percent change","%"], old:["old value",""], neu:["new value",""] },
    solve:[ {for:"pct",needs:["old","neu"],fn:function(x){return (x.neu-x.old)/x.old*100}} ],
    ex:{ for:"pct", vals:{old:40,neu:52}, says:"A price that went from 40 to 52." },
    why:"Going up 50 percent then down 50 percent does not get you back where you started. Try it and see.",
    tags:"percent increase decrease price growth" },

  { id:"mean", sub:"math", t:"Average (mean)", f:"mean = total ÷ how many", age:"9+",
    m:"Add everything up, then share it out evenly.",
    vars:{ mean:["average",""], total:["sum of all values",""], count:["how many values",""] },
    solve:[ {for:"mean",needs:["total","count"],fn:function(x){return x.total/x.count}},
            {for:"total",needs:["mean","count"],fn:function(x){return x.mean*x.count}} ],
    ex:{ for:"mean", vals:{total:441,count:5}, says:"Five test scores adding up to 441." },
    why:"One huge value drags a mean badly off centre, which is why house prices are usually reported as a median instead.",
    tags:"average mean statistics scores" },

  { id:"probability", sub:"math", t:"Simple Probability", f:"P = ways it can happen ÷ total ways", age:"10+",
    m:"The chance of something happening, as a number between 0 and 1.",
    vars:{ P:["probability",""], ways:["favourable outcomes",""], total:["total outcomes",""] },
    solve:[ {for:"P",needs:["ways","total"],fn:function(x){return x.ways/x.total}} ],
    ex:{ for:"P", vals:{ways:1,total:6}, says:"Rolling a 4 on one ordinary die." },
    why:"Multiply by 100 to get a percentage. A probability of 1 means certain, and 0 means never.",
    tags:"chance odds dice random luck" },

  { id:"quadratic", sub:"math", t:"Quadratic Formula", f:"x = (−b ± √(b² − 4ac)) ÷ 2a", age:"14+",
    m:"Solves any equation shaped like ax² + bx + c = 0. This calculator gives the first root.",
    vars:{ x:["one solution",""], a:["a",""], b:["b",""], c:["c",""] },
    solve:[ {for:"x",needs:["a","b","c"],fn:function(x){return (-x.b+Math.sqrt(x.b*x.b-4*x.a*x.c))/(2*x.a)}} ],
    ex:{ for:"x", vals:{a:1,b:-5,c:6}, says:"Solving x² − 5x + 6 = 0. The two answers are 3 and 2." },
    why:"If b² − 4ac comes out negative there are no real answers, and the parabola never crosses the axis.",
    tags:"quadratic roots parabola algebra solve" },

  { id:"compound-interest", sub:"math", t:"Compound Interest", f:"A = P × (1 + r)ⁿ", age:"13+",
    m:"Money that earns interest on the interest it already earned.",
    vars:{ A:["final amount",""], P:["starting amount",""], r:["yearly rate (0.05 = 5%)",""], n:["years",""] },
    solve:[ {for:"A",needs:["P","r","n"],fn:function(x){return x.P*Math.pow(1+x.r,x.n)}} ],
    ex:{ for:"A", vals:{P:1000,r:0.07,n:10}, says:"1000 saved at 7 percent a year, left alone for 10 years." },
    why:"The same formula describes bacteria in a dish and followers on a channel. Growth on top of growth.",
    tags:"money savings growth exponential bank" },

  { id:"scientific-notation", sub:"math", t:"Scientific Notation", f:"a × 10ⁿ", age:"12+",
    m:"A short way to write very big or very small numbers.",
    vars:{ out:["the full number",""], a:["the digits (1 to 10)",""], n:["power of ten",""] },
    solve:[ {for:"out",needs:["a","n"],fn:function(x){return x.a*Math.pow(10,x.n)}} ],
    ex:{ for:"out", vals:{a:3,n:8}, says:"The speed of light, 3 × 10⁸ metres per second." },
    why:"A positive power moves the decimal point right and a negative one moves it left. That is the whole trick.",
    tags:"powers of ten big numbers small exponent" },

  { id:"radians", sub:"math", t:"Degrees to Radians", f:"radians = degrees × π ÷ 180", age:"14+",
    m:"Two ways of measuring the same angle. Computers almost always want radians.",
    vars:{ rad:["radians","rad"], deg:["degrees","°"] },
    solve:[ {for:"rad",needs:["deg"],fn:function(x){return x.deg*Math.PI/180}},
            {for:"deg",needs:["rad"],fn:function(x){return x.rad*180/Math.PI}} ],
    ex:{ for:"rad", vals:{deg:90}, says:"A right angle, 90 degrees." },
    why:"Every sin and cos in JavaScript expects radians. Forgetting this is why so many first games spin wrong.",
    tags:"angle degrees radians trigonometry code sin cos" }
  ]);

  cards = cards.concat([
  { id:"lever", sub:"engineering", t:"The Law of the Lever", f:"F₁ × d₁ = F₂ × d₂", age:"10+",
    m:"A small force far from the pivot balances a big force close to it.",
    vars:{ F1:["effort force","N"], d1:["effort distance from pivot","m"], F2:["load force","N"], d2:["load distance from pivot","m"] },
    solve:[ {for:"F1",needs:["F2","d2","d1"],fn:function(x){return x.F2*x.d2/x.d1}},
            {for:"d1",needs:["F1","F2","d2"],fn:function(x){return x.F2*x.d2/x.F1}} ],
    ex:{ for:"F1", vals:{F2:500,d2:0.4,d1:2}, says:"Lifting a 500 N rock with a 2 m crowbar, pivot 0.4 m from the rock." },
    why:"Give me a lever long enough and I will move the world. Archimedes was not exaggerating, just being impractical.",
    tags:"lever pivot seesaw crowbar balance archimedes" },

  { id:"mech-advantage", sub:"engineering", t:"Mechanical Advantage", f:"MA = load ÷ effort", age:"11+",
    m:"How many times a machine multiplies your force.",
    vars:{ MA:["mechanical advantage",""], load:["load force","N"], effort:["effort force","N"] },
    solve:[ {for:"MA",needs:["load","effort"],fn:function(x){return x.load/x.effort}},
            {for:"effort",needs:["load","MA"],fn:function(x){return x.load/x.MA}} ],
    ex:{ for:"MA", vals:{load:900,effort:150}, says:"Lifting 900 N using only 150 N of effort." },
    why:"Machines never give you free energy. Six times the force means you have to move six times as far.",
    tags:"machine force multiplier lever pulley ramp" },

  { id:"torque", sub:"engineering", t:"Torque", f:"τ = F × r", age:"12+",
    m:"Turning force. The same push further out from the centre turns much harder.",
    vars:{ tau:["torque","N·m"], F:["force","N"], r:["distance from the pivot","m"] },
    solve:[ {for:"tau",needs:["F","r"],fn:function(x){return x.F*x.r}},
            {for:"F",needs:["tau","r"],fn:function(x){return x.tau/x.r}} ],
    ex:{ for:"tau", vals:{F:200,r:0.25}, says:"Pushing with 200 N on a spanner 25 cm long." },
    why:"A longer spanner loosens a stubborn bolt not because you got stronger, but because r got bigger.",
    tags:"turning spanner wrench bolt moment engine" },

  { id:"gear-ratio", sub:"engineering", t:"Gear Ratio", f:"ratio = teeth on driven ÷ teeth on driver", age:"11+",
    m:"How gears trade speed for turning force.",
    vars:{ ratio:["gear ratio",""], driven:["teeth on driven gear",""], driver:["teeth on driver gear",""] },
    solve:[ {for:"ratio",needs:["driven","driver"],fn:function(x){return x.driven/x.driver}} ],
    ex:{ for:"ratio", vals:{driven:40,driver:10}, says:"A 10 tooth gear driving a 40 tooth gear." },
    why:"A ratio of 4 means four times the torque and a quarter of the speed. That is low gear on a bike, going uphill.",
    tags:"gears teeth bike torque speed transmission robot" },

  { id:"gear-speed", sub:"engineering", t:"Output Speed Through Gears", f:"output rpm = input rpm ÷ ratio", age:"12+",
    m:"Work out how fast the second gear spins once you know the ratio.",
    vars:{ out:["output speed","rpm"], inp:["input speed","rpm"], ratio:["gear ratio",""] },
    solve:[ {for:"out",needs:["inp","ratio"],fn:function(x){return x.inp/x.ratio}},
            {for:"inp",needs:["out","ratio"],fn:function(x){return x.out*x.ratio}} ],
    ex:{ for:"out", vals:{inp:3000,ratio:4}, says:"A motor spinning at 3000 rpm through a 4:1 gearbox." },
    why:"Hobby robot motors spin far too fast to be useful. A gearbox trades that speed for the torque to actually move.",
    tags:"rpm motor gearbox robot speed reduction" },

  { id:"pulley", sub:"engineering", t:"Pulley Advantage", f:"MA = number of supporting ropes", age:"11+",
    m:"Every rope holding up the load shares the weight.",
    vars:{ effort:["effort needed","N"], load:["load weight","N"], ropes:["supporting ropes",""] },
    solve:[ {for:"effort",needs:["load","ropes"],fn:function(x){return x.load/x.ropes}} ],
    ex:{ for:"effort", vals:{load:800,ropes:4}, says:"Lifting 800 N on a pulley system with 4 supporting ropes." },
    why:"You pull with a quarter of the force, but you have to pull four times as much rope through your hands.",
    tags:"pulley rope lifting crane block and tackle" },

  { id:"ramp", sub:"engineering", t:"Inclined Plane", f:"MA = ramp length ÷ ramp height", age:"10+",
    m:"A ramp lets you use less force by making you travel further.",
    vars:{ MA:["mechanical advantage",""], L:["ramp length","m"], h:["ramp height","m"] },
    solve:[ {for:"MA",needs:["L","h"],fn:function(x){return x.L/x.h}} ],
    ex:{ for:"MA", vals:{L:6,h:1}, says:"A 6 m ramp rising 1 m." },
    why:"Wheelchair ramps are built long on purpose. The gentler the slope, the less force it takes to climb.",
    tags:"ramp slope incline wheelchair loading" },

  { id:"stress", sub:"engineering", t:"Stress", f:"σ = F ÷ A", age:"14+",
    m:"How hard a material is being squeezed or stretched, per unit of area.",
    vars:{ sig:["stress","Pa"], F:["force","N"], A:["cross section area","m²"] },
    solve:[ {for:"sig",needs:["F","A"],fn:function(x){return x.F/x.A}},
            {for:"A",needs:["F","sig"],fn:function(x){return x.F/x.sig}} ],
    ex:{ for:"sig", vals:{F:20000,A:0.0004}, says:"A 20 kN pull on a steel rod with a 4 cm² cross section." },
    why:"Materials do not fail because of force alone. They fail because of force crammed into too little area.",
    tags:"material strength load steel beam failure" },

  { id:"strain", sub:"engineering", t:"Strain", f:"ε = ΔL ÷ L", age:"14+",
    m:"How much something stretched, compared to how long it was to start with.",
    vars:{ eps:["strain",""], dL:["change in length","m"], L:["original length","m"] },
    solve:[ {for:"eps",needs:["dL","L"],fn:function(x){return x.dL/x.L}} ],
    ex:{ for:"eps", vals:{dL:0.002,L:2}, says:"A 2 m bar that stretched by 2 mm under load." },
    why:"Strain has no units, it is just a ratio. Steel fails at well under 1 percent strain, which is barely visible.",
    tags:"stretch deformation ratio material elongation" },

  { id:"youngs", sub:"engineering", t:"Young's Modulus", f:"E = σ ÷ ε", age:"15+",
    m:"How stiff a material is. Big number means it barely stretches.",
    vars:{ E:["Young's modulus","Pa"], sig:["stress","Pa"], eps:["strain",""] },
    solve:[ {for:"E",needs:["sig","eps"],fn:function(x){return x.sig/x.eps}},
            {for:"eps",needs:["sig","E"],fn:function(x){return x.sig/x.E}} ],
    ex:{ for:"E", vals:{sig:200e6,eps:0.001}, says:"Steel under 200 MPa of stress stretching 0.1 percent." },
    why:"Steel comes out around 200 GPa, rubber around 0.01 GPa. That single number is the difference between a beam and a band.",
    tags:"stiffness modulus elastic steel rubber material" },

  { id:"safety-factor", sub:"engineering", t:"Factor of Safety", f:"FoS = strength ÷ actual load", age:"13+",
    m:"How much stronger a thing is than it strictly needs to be.",
    vars:{ FoS:["factor of safety",""], strength:["failure strength","N"], load:["expected load","N"] },
    solve:[ {for:"FoS",needs:["strength","load"],fn:function(x){return x.strength/x.load}},
            {for:"strength",needs:["FoS","load"],fn:function(x){return x.FoS*x.load}} ],
    ex:{ for:"FoS", vals:{strength:50000,load:10000}, says:"A cable that breaks at 50 kN, carrying 10 kN." },
    why:"Lifts are typically built with a factor of about 10. Engineers assume the worst day, not the average one.",
    tags:"safety margin design failure elevator cable" },

  { id:"beam-moment", sub:"engineering", t:"Bending Moment (centre load)", f:"M = F × L ÷ 4", age:"15+",
    m:"The worst bending force in a simply supported beam with the weight in the middle.",
    vars:{ M:["maximum bending moment","N·m"], F:["load force","N"], L:["span between supports","m"] },
    solve:[ {for:"M",needs:["F","L"],fn:function(x){return x.F*x.L/4}} ],
    ex:{ for:"M", vals:{F:5000,L:4}, says:"A 5 kN weight in the middle of a 4 m span." },
    why:"Double the span and you double the bending. That is why long bridges need deep beams or extra supports.",
    tags:"beam bridge bending span support structure" },

  { id:"second-moment", sub:"engineering", t:"Second Moment of Area", f:"I = b × h³ ÷ 12", age:"16+",
    m:"How much a rectangular beam's shape resists bending. Depth matters far more than width.",
    vars:{ I:["second moment of area","m⁴"], b:["width","m"], h:["depth","m"] },
    solve:[ {for:"I",needs:["b","h"],fn:function(x){return x.b*Math.pow(x.h,3)/12}} ],
    ex:{ for:"I", vals:{b:0.05,h:0.2}, says:"A timber beam 50 mm wide and 200 mm deep." },
    why:"Turn that same plank on its side and it gets sixteen times stiffer. Nothing changed except which way it faces.",
    tags:"beam stiffness shape bending plank joist depth" },

  { id:"beam-deflection", sub:"engineering", t:"Beam Deflection", f:"δ = F × L³ ÷ (48 × E × I)", age:"16+",
    m:"How far a simply supported beam sags with a load in the middle.",
    vars:{ d:["deflection","m"], F:["load force","N"], L:["span","m"], E:["Young's modulus","Pa"], I:["second moment of area","m⁴"] },
    solve:[ {for:"d",needs:["F","L","E","I"],fn:function(x){return x.F*Math.pow(x.L,3)/(48*x.E*x.I)}} ],
    ex:{ for:"d", vals:{F:5000,L:4,E:10e9,I:3.33e-5}, says:"5 kN in the middle of a 4 m timber beam." },
    why:"The L³ is brutal. Doubling a span makes it sag eight times as much, so long floors bounce.",
    tags:"sag bending floor bounce beam span deflection" },

  { id:"series-r", sub:"engineering", t:"Resistors in Series", f:"R = R₁ + R₂", age:"12+",
    m:"Resistors in a line simply add up.",
    vars:{ R:["total resistance","Ω"], R1:["first resistor","Ω"], R2:["second resistor","Ω"] },
    solve:[ {for:"R",needs:["R1","R2"],fn:function(x){return x.R1+x.R2}} ],
    ex:{ for:"R", vals:{R1:220,R2:330}, says:"A 220 Ω and a 330 Ω resistor end to end." },
    why:"Only one path exists, so the current has to fight through both. Resistance piles up.",
    tags:"circuit resistors series electronics breadboard" },

  { id:"parallel-r", sub:"engineering", t:"Resistors in Parallel", f:"R = (R₁ × R₂) ÷ (R₁ + R₂)", age:"13+",
    m:"Two resistors side by side give the current a choice, so total resistance drops below either one.",
    vars:{ R:["total resistance","Ω"], R1:["first resistor","Ω"], R2:["second resistor","Ω"] },
    solve:[ {for:"R",needs:["R1","R2"],fn:function(x){return (x.R1*x.R2)/(x.R1+x.R2)}} ],
    ex:{ for:"R", vals:{R1:100,R2:100}, says:"Two identical 100 Ω resistors side by side." },
    why:"Two equal resistors in parallel always halve. Adding a second door does not make a room harder to leave.",
    tags:"circuit parallel resistors electronics current paths" },

  { id:"divider", sub:"engineering", t:"Voltage Divider", f:"V_out = V_in × R₂ ÷ (R₁ + R₂)", age:"14+",
    m:"Two resistors split a voltage into a smaller one you can actually use.",
    vars:{ Vout:["output voltage","V"], Vin:["input voltage","V"], R1:["top resistor","Ω"], R2:["bottom resistor","Ω"] },
    solve:[ {for:"Vout",needs:["Vin","R1","R2"],fn:function(x){return x.Vin*x.R2/(x.R1+x.R2)}} ],
    ex:{ for:"Vout", vals:{Vin:9,R1:10000,R2:5000}, says:"Dropping 9 V using a 10 kΩ and a 5 kΩ resistor." },
    why:"Swap one resistor for a light sensor and the output voltage now tells you how bright the room is. That is a sensor.",
    tags:"circuit voltage divider sensor arduino electronics" },

  { id:"resistive-power", sub:"engineering", t:"Power in a Resistor", f:"P = I² × R", age:"14+",
    m:"How much heat a resistor makes when current runs through it.",
    vars:{ P:["power","W"], I:["current","A"], R:["resistance","Ω"] },
    solve:[ {for:"P",needs:["I","R"],fn:function(x){return x.I*x.I*x.R}} ],
    ex:{ for:"P", vals:{I:0.02,R:330}, says:"20 mA flowing through a 330 Ω LED resistor." },
    why:"Because current is squared, doubling it makes four times the heat. It is how toasters and fuses both work.",
    tags:"heat resistor power electronics fuse toaster led" },

  { id:"flow", sub:"engineering", t:"Flow Rate", f:"Q = A × v", age:"13+",
    m:"How much fluid passes a point each second: pipe area times how fast it moves.",
    vars:{ Q:["flow rate","m³/s"], A:["pipe cross section","m²"], v:["fluid speed","m/s"] },
    solve:[ {for:"Q",needs:["A","v"],fn:function(x){return x.A*x.v}},
            {for:"v",needs:["Q","A"],fn:function(x){return x.Q/x.A}} ],
    ex:{ for:"Q", vals:{A:0.0005,v:2}, says:"Water at 2 m/s through a pipe with a 5 cm² opening." },
    why:"Squeeze a hose and the area drops, so the water has to speed up to keep Q the same. That is the whole trick.",
    tags:"pipe water hose flow plumbing speed" },

  { id:"thermal-expansion", sub:"engineering", t:"Thermal Expansion", f:"ΔL = α × L × ΔT", age:"15+",
    m:"Materials get longer when they get hotter.",
    vars:{ dL:["change in length","m"], alpha:["expansion coefficient","/°C"], L:["original length","m"], dT:["temperature change","°C"] },
    solve:[ {for:"dL",needs:["alpha","L","dT"],fn:function(x){return x.alpha*x.L*x.dT}} ],
    ex:{ for:"dL", vals:{alpha:0.000012,L:100,dT:30}, says:"A 100 m steel bridge span warming by 30 °C." },
    why:"That works out to about 3.6 cm, which is exactly why bridges have those metal expansion joints you drive over.",
    tags:"expansion heat bridge rail joint steel gap" },

  { id:"wheel-speed", sub:"engineering", t:"Wheel Speed from RPM", f:"v = π × D × rpm ÷ 60", age:"13+",
    m:"Turns how fast a wheel spins into how fast the vehicle actually moves.",
    vars:{ v:["speed","m/s"], D:["wheel diameter","m"], rpm:["wheel speed","rpm"] },
    solve:[ {for:"v",needs:["D","rpm"],fn:function(x){return Math.PI*x.D*x.rpm/60}},
            {for:"rpm",needs:["v","D"],fn:function(x){return x.v*60/(Math.PI*x.D)}} ],
    ex:{ for:"v", vals:{D:0.065,rpm:200}, says:"A hobby robot with 65 mm wheels turning at 200 rpm." },
    why:"This is the formula that tells your robot how long to drive to cross the room. Bigger wheels, same motor, faster robot.",
    tags:"robot wheels motor rpm speed distance driving" }
  ]);

  cards = cards.concat([
  { id:"light-time", sub:"space", t:"Light Travel Time", f:"t = d ÷ c", age:"11+",
    m:"How long light takes to cross a distance, at 300 million metres per second.",
    vars:{ t:["time","s"], d:["distance","m"] },
    solve:[ {for:"t",needs:["d"],fn:function(x){return x.d/3.0e8}},
            {for:"d",needs:["t"],fn:function(x){return x.t*3.0e8}} ],
    ex:{ for:"t", vals:{d:1.496e11}, says:"From the Sun to the Earth, about 1.496 × 10¹¹ metres." },
    why:"That comes out around 500 seconds, so sunlight is over eight minutes old by the time it hits your face.",
    tags:"light speed sun distance space delay" },

  { id:"escape-velocity", sub:"space", t:"Escape Velocity", f:"v = √(2 × G × M ÷ r)", age:"15+",
    m:"How fast you have to be going to leave a planet behind for good.",
    vars:{ v:["escape velocity","m/s"], M:["planet mass","kg"], r:["radius","m"] },
    solve:[ {for:"v",needs:["M","r"],fn:function(x){return Math.sqrt(2*6.674e-11*x.M/x.r)}} ],
    ex:{ for:"v", vals:{M:5.97e24,r:6371000}, says:"Leaving Earth from its surface." },
    why:"About 11 200 m/s, or 25 000 mph. The Moon's is a fifth of that, which is why leaving it was the easy part.",
    tags:"rocket space escape gravity planet moon launch" },

  { id:"kepler", sub:"space", t:"Kepler's Third Law", f:"T² = a³", age:"14+",
    m:"How long a planet takes to orbit, from how far out it is. Years and astronomical units.",
    vars:{ T:["orbit time","years"], a:["distance from Sun","AU"] },
    solve:[ {for:"T",needs:["a"],fn:function(x){return Math.sqrt(Math.pow(x.a,3))}},
            {for:"a",needs:["T"],fn:function(x){return Math.pow(x.T*x.T,1/3)}} ],
    ex:{ for:"T", vals:{a:5.2}, says:"Jupiter, 5.2 times further from the Sun than we are." },
    why:"It gives about 11.9 years, which is exactly Jupiter's real orbit. Kepler found this by staring at data for years.",
    tags:"orbit planets kepler year sun jupiter astronomy" },

  { id:"weight-planets", sub:"space", t:"Your Weight on Another World", f:"W = m × g_planet", age:"9+",
    m:"Same body, different gravity. Try g values: Moon 1.6, Mars 3.7, Earth 9.8, Jupiter 24.8.",
    vars:{ W:["weight there","N"], m:["your mass","kg"], g:["gravity there","m/s²"] },
    solve:[ {for:"W",needs:["m","g"],fn:function(x){return x.m*x.g}} ],
    ex:{ for:"W", vals:{m:40,g:1.6}, says:"A 40 kg kid standing on the Moon." },
    why:"Your mass is identical everywhere. Only the pull changes, which is why astronauts bounce instead of float.",
    tags:"gravity moon mars jupiter weight astronaut planets" },

  { id:"lightyear", sub:"space", t:"Light Years to Kilometres", f:"d = ly × 9.461×10¹²", age:"12+",
    m:"A light year is a distance, not a time: how far light travels in one year.",
    vars:{ km:["distance","km"], ly:["light years","ly"] },
    solve:[ {for:"km",needs:["ly"],fn:function(x){return x.ly*9.461e12}},
            {for:"ly",needs:["km"],fn:function(x){return x.km/9.461e12}} ],
    ex:{ for:"km", vals:{ly:4.24}, says:"Proxima Centauri, the nearest star to the Sun." },
    why:"Looking at a star 4.24 light years away means seeing light that left before you were born. Telescopes are time machines.",
    tags:"light year distance star space telescope proxima" }
  ]);

  window.FormulaCards = cards;
})();
