/**
 * Sudoku — fill the grid so every row, column and box holds 1-9 once each.
 *
 * Puzzles are generated by making a full solved grid, then removing clues one
 * at a time and putting a clue back if its removal leaves more than one
 * possible answer. That uniqueness check is the part that matters: a puzzle
 * with two answers cannot be reasoned out, only guessed at, and a child who
 * fills in a valid-looking grid that the game rejects will fairly conclude
 * the game is broken.
 */
(function () {
  "use strict";

  const boardEl = document.getElementById("su-board");
  if (!boardEl) return;

  const LEVELS = {
    easy: { label: "🐣 Easy", clues: 42 },
    medium: { label: "🐤 Medium", clues: 34 },
    hard: { label: "🦅 Hard", clues: 28 },
  };

  const LEVEL_KEY = "sudoku-level";
  const BEST_KEY = "sudoku-best";

  const state = {
    levelId: "easy",
    puzzle: [],        // the givens, 0 = blank
    solution: [],
    grid: [],          // what the player has entered
    notes: [],         // Set per cell
    selected: null,    // [r, c]
    noteMode: false,
    mistakes: 0,
    elapsed: 0,
    startedAt: 0,
    solved: false,
    best: {},
  };

  let soundOn = true;
  let audioCtx = null;
  let tickTimer = null;

  const el = {
    board: boardEl,
    pad: document.getElementById("su-pad"),
    status: document.getElementById("su-status"),
    time: document.getElementById("su-time"),
    empty: document.getElementById("su-empty"),
    mistakes: document.getElementById("su-mistakes"),
    best: document.getElementById("su-best"),
    restart: document.getElementById("btn-restart"),
    noteBtn: document.getElementById("btn-notes"),
    checkBtn: document.getElementById("btn-check"),
    sound: document.getElementById("btn-sound"),
  };

  /* ---------- Sound ---------- */
  function beep(freq, duration, type) {
    if (!soundOn) return;
    try {
      const AudioCtor = window.AudioContext || window.webkitAudioContext;
      if (!AudioCtor) return;
      if (!audioCtx) audioCtx = new AudioCtor();
      if (audioCtx.state === "suspended") audioCtx.resume();
      const osc = audioCtx.createOscillator();
      const gain = audioCtx.createGain();
      osc.type = type || "sine";
      osc.frequency.value = freq;
      gain.gain.setValueAtTime(0.05, audioCtx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.0001, audioCtx.currentTime + duration);
      osc.connect(gain);
      gain.connect(audioCtx.destination);
      osc.start();
      osc.stop(audioCtx.currentTime + duration);
    } catch (err) { /* optional */ }
  }

  function fanfare() {
    [523, 659, 784, 1047].forEach((f, i) => window.setTimeout(() => beep(f, 0.18, "triangle"), i * 130));
  }

  /* ---------- Sudoku maths ---------- */
  function emptyGrid() {
    return Array.from({ length: 9 }, () => new Array(9).fill(0));
  }

  function cloneGrid(grid) {
    return grid.map((row) => row.slice());
  }

  /** Can `value` go at (row, col) without clashing? */
  function allowed(grid, row, col, value) {
    for (let i = 0; i < 9; i++) {
      if (grid[row][i] === value && i !== col) return false;
      if (grid[i][col] === value && i !== row) return false;
    }
    const boxRow = Math.floor(row / 3) * 3;
    const boxCol = Math.floor(col / 3) * 3;
    for (let r = boxRow; r < boxRow + 3; r++) {
      for (let c = boxCol; c < boxCol + 3; c++) {
        if (grid[r][c] === value && !(r === row && c === col)) return false;
      }
    }
    return true;
  }

  function shuffled(list) {
    const out = list.slice();
    for (let i = out.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const swap = out[i]; out[i] = out[j]; out[j] = swap;
    }
    return out;
  }

  function firstEmpty(grid) {
    for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) if (grid[r][c] === 0) return [r, c];
    return null;
  }

  /** Fill a blank grid with a random valid solution. */
  function fillGrid(grid) {
    const spot = firstEmpty(grid);
    if (!spot) return true;
    const [row, col] = spot;
    for (const value of shuffled([1, 2, 3, 4, 5, 6, 7, 8, 9])) {
      if (!allowed(grid, row, col, value)) continue;
      grid[row][col] = value;
      if (fillGrid(grid)) return true;
      grid[row][col] = 0;
    }
    return false;
  }

  /** Counts solutions, stopping at `limit` — we only ever care about "more than one". */
  function countSolutions(grid, limit) {
    const spot = firstEmpty(grid);
    if (!spot) return 1;
    const [row, col] = spot;
    let found = 0;
    for (let value = 1; value <= 9; value++) {
      if (!allowed(grid, row, col, value)) continue;
      grid[row][col] = value;
      found += countSolutions(grid, limit - found);
      grid[row][col] = 0;
      if (found >= limit) break;
    }
    return found;
  }

  function makePuzzle(clues) {
    const solution = emptyGrid();
    fillGrid(solution);
    const puzzle = cloneGrid(solution);

    let filled = 81;
    // Remove clues in a random order, but put one back if the puzzle stops
    // having exactly one answer.
    for (const index of shuffled(Array.from({ length: 81 }, (_, i) => i))) {
      if (filled <= clues) break;
      const row = Math.floor(index / 9), col = index % 9;
      if (puzzle[row][col] === 0) continue;
      const removed = puzzle[row][col];
      puzzle[row][col] = 0;
      if (countSolutions(cloneGrid(puzzle), 2) !== 1) {
        puzzle[row][col] = removed;   // ambiguous — keep the clue
      } else {
        filled -= 1;
      }
    }
    return { puzzle, solution };
  }

  /* ---------- Timer ---------- */
  function startTimer() {
    if (tickTimer) return;
    state.startedAt = Date.now() - state.elapsed;
    tickTimer = window.setInterval(() => {
      state.elapsed = Date.now() - state.startedAt;
      renderStats();
    }, 250);
  }

  function stopTimer() {
    if (!tickTimer) return;
    window.clearInterval(tickTimer);
    tickTimer = null;
  }

  function formatTime(ms) {
    const total = Math.floor(ms / 1000);
    return Math.floor(total / 60) + ":" + String(total % 60).padStart(2, "0");
  }

  /* ---------- Best times ---------- */
  function loadBest() {
    try {
      const parsed = JSON.parse(window.localStorage.getItem(BEST_KEY) || "{}");
      state.best = parsed && typeof parsed === "object" ? parsed : {};
    } catch (err) { state.best = {}; }
  }

  function bestForCurrent() {
    const value = state.best[state.levelId];
    return typeof value === "number" ? value : null;
  }

  function recordBest() {
    const previous = bestForCurrent();
    if (previous !== null && state.elapsed >= previous) return false;
    state.best[state.levelId] = state.elapsed;
    try { window.localStorage.setItem(BEST_KEY, JSON.stringify(state.best)); } catch (err) { /* ok */ }
    return true;
  }

  /* ---------- Play ---------- */
  function isGiven(r, c) { return state.puzzle[r][c] !== 0; }

  function emptyCount() {
    let count = 0;
    for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) if (state.grid[r][c] === 0) count++;
    return count;
  }

  function newGame() {
    const cfg = LEVELS[state.levelId] || LEVELS.easy;
    stopTimer();
    const made = makePuzzle(cfg.clues);
    state.puzzle = made.puzzle;
    state.solution = made.solution;
    state.grid = cloneGrid(made.puzzle);
    state.notes = Array.from({ length: 9 }, () => Array.from({ length: 9 }, () => new Set()));
    state.selected = null;
    state.mistakes = 0;
    state.elapsed = 0;
    state.solved = false;
    render();
    setStatus("Fill every row, column and box with 1 to 9.");
  }

  function select(r, c) {
    if (state.solved) return;
    state.selected = [r, c];
    render();
  }

  function enter(value) {
    if (state.solved || !state.selected) return;
    const [r, c] = state.selected;
    if (isGiven(r, c)) return;
    if (!tickTimer) startTimer();

    if (state.noteMode && value !== 0) {
      const notes = state.notes[r][c];
      if (notes.has(value)) notes.delete(value); else notes.add(value);
      beep(500, 0.03, "sine");
      render();
      return;
    }

    if (value === 0) {
      state.grid[r][c] = 0;
      state.notes[r][c].clear();
      render();
      return;
    }

    state.grid[r][c] = value;
    state.notes[r][c].clear();

    if (value !== state.solution[r][c]) {
      state.mistakes += 1;
      beep(200, 0.12, "square");
      setStatus("That one doesn't fit — the wrong numbers are marked in red.");
    } else {
      beep(620, 0.05, "sine");
      setStatus("");
    }

    checkSolved();
    render();
  }

  function checkSolved() {
    for (let r = 0; r < 9; r++) {
      for (let c = 0; c < 9; c++) {
        if (state.grid[r][c] !== state.solution[r][c]) return;
      }
    }
    state.solved = true;
    stopTimer();
    const isBest = recordBest();
    fanfare();
    setStatus(isBest
      ? "🏆 Solved in " + formatTime(state.elapsed) + " — a new best!"
      : "🎉 Solved in " + formatTime(state.elapsed) + "!");
  }

  /** Fills in a single square the player has left blank. */
  function giveHint() {
    if (state.solved) return;
    const blanks = [];
    for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++)
      if (state.grid[r][c] !== state.solution[r][c]) blanks.push([r, c]);
    if (!blanks.length) return;
    const [r, c] = blanks[Math.floor(Math.random() * blanks.length)];
    state.selected = [r, c];
    state.grid[r][c] = state.solution[r][c];
    state.notes[r][c].clear();
    if (!tickTimer) startTimer();
    beep(760, 0.1, "triangle");
    setStatus("💡 Filled one in for you.");
    checkSolved();
    render();
  }

  /* ---------- Rendering ---------- */
  function render() {
    el.board.innerHTML = "";
    const grid = document.createElement("div");
    grid.className = "su-grid";

    const selected = state.selected;
    const selectedValue = selected ? state.grid[selected[0]][selected[1]] : 0;

    for (let r = 0; r < 9; r++) {
      for (let c = 0; c < 9; c++) {
        const value = state.grid[r][c];
        const given = isGiven(r, c);
        const wrong = value !== 0 && value !== state.solution[r][c];
        const isSelected = selected && selected[0] === r && selected[1] === c;
        const sameLine = selected && !isSelected &&
          (selected[0] === r || selected[1] === c ||
           (Math.floor(selected[0] / 3) === Math.floor(r / 3) && Math.floor(selected[1] / 3) === Math.floor(c / 3)));
        const sameValue = value !== 0 && value === selectedValue && !isSelected;

        const cell = document.createElement("button");
        cell.type = "button";
        cell.className = "su-cell" +
          (given ? " is-given" : "") +
          (wrong ? " is-wrong" : "") +
          (isSelected ? " is-selected" : "") +
          (sameLine ? " is-peer" : "") +
          (sameValue ? " is-same" : "") +
          (c % 3 === 2 && c !== 8 ? " box-right" : "") +
          (r % 3 === 2 && r !== 8 ? " box-bottom" : "");

        if (value !== 0) {
          cell.textContent = String(value);
        } else if (state.notes[r][c].size) {
          const notes = document.createElement("span");
          notes.className = "su-notes";
          for (let n = 1; n <= 9; n++) {
            const note = document.createElement("span");
            note.textContent = state.notes[r][c].has(n) ? String(n) : "";
            notes.appendChild(note);
          }
          cell.appendChild(notes);
        }

        cell.setAttribute("aria-label", "Row " + (r + 1) + " column " + (c + 1) + ", " +
          (value === 0 ? "empty" : value + (given ? " given" : wrong ? ", wrong" : "")));
        cell.disabled = state.solved;
        cell.addEventListener("click", () => select(r, c));
        grid.appendChild(cell);
      }
    }
    el.board.appendChild(grid);

    // Number pad, with digits that are already used up dimmed.
    el.pad.innerHTML = "";
    for (let n = 1; n <= 9; n++) {
      let placed = 0;
      for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) if (state.grid[r][c] === n) placed++;
      const button = document.createElement("button");
      button.type = "button";
      button.className = "su-key" + (placed >= 9 ? " is-done" : "");
      button.textContent = String(n);
      button.setAttribute("aria-label", n + (placed >= 9 ? ", all placed" : ""));
      button.disabled = state.solved;
      button.addEventListener("click", () => enter(n));
      el.pad.appendChild(button);
    }
    const erase = document.createElement("button");
    erase.type = "button";
    erase.className = "su-key su-key--erase";
    erase.textContent = "⌫";
    erase.setAttribute("aria-label", "Erase");
    erase.disabled = state.solved;
    erase.addEventListener("click", () => enter(0));
    el.pad.appendChild(erase);

    renderStats();
  }

  function renderStats() {
    el.time.textContent = formatTime(state.elapsed);
    el.empty.textContent = String(emptyCount());
    el.mistakes.textContent = String(state.mistakes);
    const best = bestForCurrent();
    el.best.textContent = best === null ? "—" : formatTime(best);
    el.noteBtn.textContent = state.noteMode ? "✏️ Notes: On" : "✏️ Notes: Off";
    el.noteBtn.setAttribute("aria-pressed", String(state.noteMode));
  }

  function setStatus(text) { el.status.textContent = text; }

  /* ---------- Wiring ---------- */
  el.restart.addEventListener("click", () => {
    setStatus("Building a new puzzle…");
    // Let the status paint before the generator blocks for a moment.
    window.setTimeout(newGame, 20);
  });
  el.noteBtn.addEventListener("click", () => {
    state.noteMode = !state.noteMode;
    renderStats();
    setStatus(state.noteMode
      ? "Notes on — tapping a number now pencils it in small."
      : "Notes off — tapping a number fills the square in.");
  });
  el.checkBtn.addEventListener("click", giveHint);
  el.sound.addEventListener("click", () => {
    soundOn = !soundOn;
    el.sound.textContent = soundOn ? "🔊 Sound On" : "🔇 Sound Off";
    el.sound.setAttribute("aria-pressed", String(soundOn));
  });

  document.querySelectorAll("[data-level]").forEach((button) => {
    button.addEventListener("click", () => {
      state.levelId = button.dataset.level;
      try { window.localStorage.setItem(LEVEL_KEY, state.levelId); } catch (err) { /* ok */ }
      document.querySelectorAll("[data-level]").forEach((other) => {
        const active = other === button;
        other.classList.toggle("is-active", active);
        other.setAttribute("aria-pressed", String(active));
      });
      setStatus("Building a new puzzle…");
      window.setTimeout(newGame, 20);
    });
  });

  window.addEventListener("keydown", (event) => {
    const digit = /^(?:Digit|Numpad)([0-9])$/.exec(event.code);
    if (digit) { event.preventDefault(); enter(Number(digit[1])); return; }
    if (event.code === "Backspace" || event.code === "Delete") { event.preventDefault(); enter(0); return; }
    if (event.code === "KeyN") { event.preventDefault(); state.noteMode = !state.noteMode; renderStats(); return; }
    const moves = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1] };
    const move = moves[event.code];
    if (!move || !state.selected) return;
    event.preventDefault();
    const r = Math.max(0, Math.min(8, state.selected[0] + move[0]));
    const c = Math.max(0, Math.min(8, state.selected[1] + move[1]));
    select(r, c);
  });

  try {
    const saved = window.localStorage.getItem(LEVEL_KEY);
    if (saved && LEVELS[saved]) state.levelId = saved;
  } catch (err) { /* defaults fine */ }

  document.querySelectorAll("[data-level]").forEach((button) => {
    const active = button.dataset.level === state.levelId;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });

  loadBest();
  newGame();

  window.SudokuGame = {
    state, LEVELS, emptyGrid, cloneGrid, allowed, fillGrid, countSolutions, makePuzzle,
    newGame, enter, select, giveHint, checkSolved, isGiven,
  };
})();
