/**
 * The periodic table — all 118 elements.
 *
 * Each row is [atomic number, symbol, name, group, period, category].
 *
 *   group   the column, 1-18. Lanthanides and actinides use 0, because they
 *           sit in the two rows underneath rather than in the main grid.
 *   period  the row, 1-7.
 *
 * The offline tests check this list is complete and consistent: every atomic
 * number from 1 to 118 exactly once, no repeated symbols or names, every
 * position inside the grid, and no two elements in the same square. Getting a
 * fact wrong here would teach a child something false, so it is checked rather
 * than trusted.
 */
(function () {
  "use strict";

  const ALKALI = "alkali", ALKALINE = "alkaline", TRANSITION = "transition",
        POST = "post", METALLOID = "metalloid", NONMETAL = "nonmetal",
        HALOGEN = "halogen", NOBLE = "noble", LANTHANIDE = "lanthanide",
        ACTINIDE = "actinide";

  const RAW = [
    [1, "H", "Hydrogen", 1, 1, NONMETAL],
    [2, "He", "Helium", 18, 1, NOBLE],
    [3, "Li", "Lithium", 1, 2, ALKALI],
    [4, "Be", "Beryllium", 2, 2, ALKALINE],
    [5, "B", "Boron", 13, 2, METALLOID],
    [6, "C", "Carbon", 14, 2, NONMETAL],
    [7, "N", "Nitrogen", 15, 2, NONMETAL],
    [8, "O", "Oxygen", 16, 2, NONMETAL],
    [9, "F", "Fluorine", 17, 2, HALOGEN],
    [10, "Ne", "Neon", 18, 2, NOBLE],
    [11, "Na", "Sodium", 1, 3, ALKALI],
    [12, "Mg", "Magnesium", 2, 3, ALKALINE],
    [13, "Al", "Aluminium", 13, 3, POST],
    [14, "Si", "Silicon", 14, 3, METALLOID],
    [15, "P", "Phosphorus", 15, 3, NONMETAL],
    [16, "S", "Sulfur", 16, 3, NONMETAL],
    [17, "Cl", "Chlorine", 17, 3, HALOGEN],
    [18, "Ar", "Argon", 18, 3, NOBLE],
    [19, "K", "Potassium", 1, 4, ALKALI],
    [20, "Ca", "Calcium", 2, 4, ALKALINE],
    [21, "Sc", "Scandium", 3, 4, TRANSITION],
    [22, "Ti", "Titanium", 4, 4, TRANSITION],
    [23, "V", "Vanadium", 5, 4, TRANSITION],
    [24, "Cr", "Chromium", 6, 4, TRANSITION],
    [25, "Mn", "Manganese", 7, 4, TRANSITION],
    [26, "Fe", "Iron", 8, 4, TRANSITION],
    [27, "Co", "Cobalt", 9, 4, TRANSITION],
    [28, "Ni", "Nickel", 10, 4, TRANSITION],
    [29, "Cu", "Copper", 11, 4, TRANSITION],
    [30, "Zn", "Zinc", 12, 4, TRANSITION],
    [31, "Ga", "Gallium", 13, 4, POST],
    [32, "Ge", "Germanium", 14, 4, METALLOID],
    [33, "As", "Arsenic", 15, 4, METALLOID],
    [34, "Se", "Selenium", 16, 4, NONMETAL],
    [35, "Br", "Bromine", 17, 4, HALOGEN],
    [36, "Kr", "Krypton", 18, 4, NOBLE],
    [37, "Rb", "Rubidium", 1, 5, ALKALI],
    [38, "Sr", "Strontium", 2, 5, ALKALINE],
    [39, "Y", "Yttrium", 3, 5, TRANSITION],
    [40, "Zr", "Zirconium", 4, 5, TRANSITION],
    [41, "Nb", "Niobium", 5, 5, TRANSITION],
    [42, "Mo", "Molybdenum", 6, 5, TRANSITION],
    [43, "Tc", "Technetium", 7, 5, TRANSITION],
    [44, "Ru", "Ruthenium", 8, 5, TRANSITION],
    [45, "Rh", "Rhodium", 9, 5, TRANSITION],
    [46, "Pd", "Palladium", 10, 5, TRANSITION],
    [47, "Ag", "Silver", 11, 5, TRANSITION],
    [48, "Cd", "Cadmium", 12, 5, TRANSITION],
    [49, "In", "Indium", 13, 5, POST],
    [50, "Sn", "Tin", 14, 5, POST],
    [51, "Sb", "Antimony", 15, 5, METALLOID],
    [52, "Te", "Tellurium", 16, 5, METALLOID],
    [53, "I", "Iodine", 17, 5, HALOGEN],
    [54, "Xe", "Xenon", 18, 5, NOBLE],
    [55, "Cs", "Caesium", 1, 6, ALKALI],
    [56, "Ba", "Barium", 2, 6, ALKALINE],
    [57, "La", "Lanthanum", 0, 6, LANTHANIDE],
    [58, "Ce", "Cerium", 0, 6, LANTHANIDE],
    [59, "Pr", "Praseodymium", 0, 6, LANTHANIDE],
    [60, "Nd", "Neodymium", 0, 6, LANTHANIDE],
    [61, "Pm", "Promethium", 0, 6, LANTHANIDE],
    [62, "Sm", "Samarium", 0, 6, LANTHANIDE],
    [63, "Eu", "Europium", 0, 6, LANTHANIDE],
    [64, "Gd", "Gadolinium", 0, 6, LANTHANIDE],
    [65, "Tb", "Terbium", 0, 6, LANTHANIDE],
    [66, "Dy", "Dysprosium", 0, 6, LANTHANIDE],
    [67, "Ho", "Holmium", 0, 6, LANTHANIDE],
    [68, "Er", "Erbium", 0, 6, LANTHANIDE],
    [69, "Tm", "Thulium", 0, 6, LANTHANIDE],
    [70, "Yb", "Ytterbium", 0, 6, LANTHANIDE],
    [71, "Lu", "Lutetium", 0, 6, LANTHANIDE],
    [72, "Hf", "Hafnium", 4, 6, TRANSITION],
    [73, "Ta", "Tantalum", 5, 6, TRANSITION],
    [74, "W", "Tungsten", 6, 6, TRANSITION],
    [75, "Re", "Rhenium", 7, 6, TRANSITION],
    [76, "Os", "Osmium", 8, 6, TRANSITION],
    [77, "Ir", "Iridium", 9, 6, TRANSITION],
    [78, "Pt", "Platinum", 10, 6, TRANSITION],
    [79, "Au", "Gold", 11, 6, TRANSITION],
    [80, "Hg", "Mercury", 12, 6, TRANSITION],
    [81, "Tl", "Thallium", 13, 6, POST],
    [82, "Pb", "Lead", 14, 6, POST],
    [83, "Bi", "Bismuth", 15, 6, POST],
    [84, "Po", "Polonium", 16, 6, POST],
    [85, "At", "Astatine", 17, 6, HALOGEN],
    [86, "Rn", "Radon", 18, 6, NOBLE],
    [87, "Fr", "Francium", 1, 7, ALKALI],
    [88, "Ra", "Radium", 2, 7, ALKALINE],
    [89, "Ac", "Actinium", 0, 7, ACTINIDE],
    [90, "Th", "Thorium", 0, 7, ACTINIDE],
    [91, "Pa", "Protactinium", 0, 7, ACTINIDE],
    [92, "U", "Uranium", 0, 7, ACTINIDE],
    [93, "Np", "Neptunium", 0, 7, ACTINIDE],
    [94, "Pu", "Plutonium", 0, 7, ACTINIDE],
    [95, "Am", "Americium", 0, 7, ACTINIDE],
    [96, "Cm", "Curium", 0, 7, ACTINIDE],
    [97, "Bk", "Berkelium", 0, 7, ACTINIDE],
    [98, "Cf", "Californium", 0, 7, ACTINIDE],
    [99, "Es", "Einsteinium", 0, 7, ACTINIDE],
    [100, "Fm", "Fermium", 0, 7, ACTINIDE],
    [101, "Md", "Mendelevium", 0, 7, ACTINIDE],
    [102, "No", "Nobelium", 0, 7, ACTINIDE],
    [103, "Lr", "Lawrencium", 0, 7, ACTINIDE],
    [104, "Rf", "Rutherfordium", 4, 7, TRANSITION],
    [105, "Db", "Dubnium", 5, 7, TRANSITION],
    [106, "Sg", "Seaborgium", 6, 7, TRANSITION],
    [107, "Bh", "Bohrium", 7, 7, TRANSITION],
    [108, "Hs", "Hassium", 8, 7, TRANSITION],
    [109, "Mt", "Meitnerium", 9, 7, TRANSITION],
    [110, "Ds", "Darmstadtium", 10, 7, TRANSITION],
    [111, "Rg", "Roentgenium", 11, 7, TRANSITION],
    [112, "Cn", "Copernicium", 12, 7, TRANSITION],
    [113, "Nh", "Nihonium", 13, 7, POST],
    [114, "Fl", "Flerovium", 14, 7, POST],
    [115, "Mc", "Moscovium", 15, 7, POST],
    [116, "Lv", "Livermorium", 16, 7, POST],
    [117, "Ts", "Tennessine", 17, 7, HALOGEN],
    [118, "Og", "Oganesson", 18, 7, NOBLE]
  ];

  /** A short, true, child-sized note for the ones a child is likely to meet. */
  const NOTES = {
    H: "The lightest thing there is, and the most common stuff in the universe.",
    He: "Makes balloons float, and makes your voice go squeaky.",
    Li: "Inside the battery of almost every phone and tablet.",
    C: "You are mostly made of this. So are diamonds and pencil lead.",
    N: "Most of the air you breathe is this, not oxygen.",
    O: "The bit of air you actually need. Also half of water.",
    Ne: "Glows orange-red in signs. That is where neon lights get their name.",
    Na: "Half of salt. On its own it fizzes and burns in water.",
    Mg: "Burns with a blinding white light. Plants need it to be green.",
    Al: "Drinks cans and kitchen foil. Light, and it never rusts.",
    Si: "Sand, glass, and the chip inside every computer.",
    Cl: "Half of salt, and what keeps swimming pools clean.",
    K: "Bananas are famous for it. Your muscles need it.",
    Ca: "Bones, teeth, chalk and eggshells.",
    Ti: "As strong as steel but much lighter. Used in aeroplanes.",
    Fe: "Steel is mostly this. It is also what makes your blood red.",
    Cu: "The orange metal inside wires and old pennies.",
    Zn: "Coats nails and bolts to stop them rusting.",
    Ag: "Silver. The best conductor of electricity there is.",
    Sn: "Tin. Mixed with copper it makes bronze.",
    I: "Painted on cuts to kill germs. Your body needs a tiny bit.",
    Xe: "Used in very bright car headlights and lighthouse lamps.",
    W: "Tungsten. Melts at a higher temperature than anything else.",
    Pt: "Platinum. Rarer than gold, and used in jewellery.",
    Au: "Gold. It never tarnishes, which is why treasure still shines.",
    Hg: "The only metal that is liquid at room temperature.",
    Pb: "Lead. Very heavy and rather poisonous.",
    U: "Uranium. Its atoms can be split to make electricity."
  };

  window.Elements = RAW.map((row) => ({
    z: row[0],
    symbol: row[1],
    name: row[2],
    group: row[3],
    period: row[4],
    category: row[5],
    note: NOTES[row[1]] || "",
    // Where it sits on screen. The f-block gets its own two rows underneath.
    col: row[3] === 0 ? 3 + (row[0] - (row[4] === 6 ? 57 : 89)) : row[3],
    row: row[3] === 0 ? (row[4] === 6 ? 9 : 10) : row[4]
  }));

  window.ElementCategories = [
    { id: ALKALI, label: "Alkali metal", colour: "#ff8a6b" },
    { id: ALKALINE, label: "Alkaline earth", colour: "#ffc46b" },
    { id: TRANSITION, label: "Transition metal", colour: "#ffe08a" },
    { id: POST, label: "Metal", colour: "#bfe3a0" },
    { id: METALLOID, label: "Metalloid", colour: "#8fd6c4" },
    { id: NONMETAL, label: "Non-metal", colour: "#8ec9f0" },
    { id: HALOGEN, label: "Halogen", colour: "#b7aef5" },
    { id: NOBLE, label: "Noble gas", colour: "#f0a8d8" },
    { id: LANTHANIDE, label: "Lanthanide", colour: "#d9c2a6" },
    { id: ACTINIDE, label: "Actinide", colour: "#c9b0c8" }
  ];
})();
